import {
  Astro,
  AstroDark,
  DarkDeno,
  DarkExpressjs,
  DarkPrisma,
  DarkVercel,
  Deno,
  Docker,
  Expressjs,
  Git,
  JavaScript,
  Neon,
  NestJS,
  Nextjs,
  Nodejs,
  PostgreSQL,
  Prisma,
  Python,
  RadixUI,
  RadixUIDark,
  React,
  Redux,
  Sass,
  Sentry,
  shadcnui,
  shadcnuiDark,
  StyledComponents,
  TailwindCSS,
  TypeScript,
  Vercel,
  Vite,
  Vitest,
} from '@/assets/icons/allIcons';
import {
  AntDesign,
  BaseUI,
  BetterAuth,
  CSSNew,
  DarkBaseUI,
  DarkBetterAuth,
  DarkDrizzleORM,
  DarkESLintIcon,
  DarkFlask,
  DarkMarkdown,
  DarkMotionSvgl,
  DarkNx,
  DarkPHP,
  DarkPrettierIcon,
  DarkRemix,
  DarkSocketIOSvgl,
  DarkTurborepo,
  DrizzleORM,
  ElysiaJS,
  ESLintIcon,
  ExpoSvgl,
  Flask,
  Hono,
  HTML5,
  JestSvgl,
  Laravel,
  Mantine,
  Markdown,
  MaterialUI,
  MotionSvgl,
  Nx,
  PHP,
  PrettierIcon,
  ReactQuery,
  Remix,
  SocketIOSvgl,
  Turborepo,
} from '@/assets/icons/svgl-proxy-icons';
import { type SVGProps } from 'react';

export type SvglIcon = (props: SVGProps<SVGSVGElement>) => JSX.Element;
export type Technology = {
  Icon: SvglIcon;
  name: string;
  docs?: string;
  customGlowColor?: string;
  DarkIcon?: SvglIcon;
};

export const technologies: Technology[] = [
  // Lo que los reclutadores buscan primero
  {
    Icon: React,
    name: 'React',
    docs: 'https://react.dev/',
  },
  {
    Icon: Nextjs,
    name: 'Next.js',
    docs: 'https://nextjs.org/docs',
    customGlowColor: '#ffffff',
  },
  {
    Icon: TypeScript,
    name: 'TypeScript',
    docs: 'https://www.typescriptlang.org/docs/',
  },
  {
    Icon: TailwindCSS,
    name: 'Tailwind CSS',
    docs: 'https://tailwindcss.com/docs',
  },
  {
    Icon: JavaScript,
    name: 'JavaScript',
    docs: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  },
  {
    Icon: Nodejs,
    name: 'Node.js',
    docs: 'https://nodejs.org/en/docs/',
    customGlowColor: '#8CC84B',
  },
  {
    Icon: Git,
    name: 'Git',
    docs: 'https://git-scm.com/doc',
  },
  {
    Icon: PostgreSQL,
    name: 'PostgreSQL',
    docs: 'https://www.postgresql.org/docs/',
    customGlowColor: '#0064a5',
  },
  {
    Icon: Docker,
    name: 'Docker',
    docs: 'https://docs.docker.com/',
    customGlowColor: '#2496ED',
  },
  {
    Icon: Python,
    name: 'Python',
    docs: 'https://docs.python.org/3/',
    customGlowColor: '#4B8BBE',
  },
  {
    Icon: PHP,
    name: 'PHP',
    docs: 'https://www.php.net/docs.php',
    customGlowColor: '#777BB3',
    DarkIcon: DarkPHP,
  },
  {
    Icon: HTML5,
    name: 'HTML5',
    docs: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
    customGlowColor: '#E34F26',
  },
  {
    Icon: CSSNew,
    name: 'CSS (New)',
    docs: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
    customGlowColor: '#1572B6',
  },
  {
    Icon: Markdown,
    name: 'Markdown',
    docs: 'https://www.markdownguide.org/',
    DarkIcon: DarkMarkdown,
  },

  // Frameworks & herramientas muy demandadas
  {
    Icon: NestJS,
    name: 'NestJS',
    docs: 'https://docs.nestjs.com/',
  },
  {
    Icon: Laravel,
    name: 'Laravel',
    docs: 'https://laravel.com/docs',
    customGlowColor: '#FF2D20',
  },
  {
    Icon: ExpoSvgl,
    name: 'Expo',
    docs: 'https://docs.expo.dev/',
  },
  {
    Icon: ElysiaJS,
    name: 'ElysiaJS',
    docs: 'https://elysiajs.com/',
  },
  {
    Icon: Flask,
    name: 'Flask',
    docs: 'https://flask.palletsprojects.com/',
    DarkIcon: DarkFlask,
  },
  {
    Icon: Remix,
    name: 'Remix',
    docs: 'https://remix.run/docs',
    DarkIcon: DarkRemix,
  },
  {
    Icon: Hono,
    name: 'Hono',
    docs: 'https://hono.dev/docs/',
    customGlowColor: '#E36002',
  },
  {
    Icon: Prisma,
    name: 'Prisma',
    docs: 'https://www.prisma.io/docs',
    DarkIcon: DarkPrisma,
  },
  {
    Icon: Redux,
    name: 'Redux',
    docs: 'https://redux.js.org/introduction/getting-started',
  },
  {
    Icon: ReactQuery,
    name: 'React Query',
    docs: 'https://tanstack.com/query/latest',
    customGlowColor: '#FF4154',
  },
  {
    Icon: DrizzleORM,
    name: 'Drizzle ORM',
    docs: 'https://orm.drizzle.team/docs/overview',
    customGlowColor: '#C5F74F',
    DarkIcon: DarkDrizzleORM,
  },
  {
    Icon: Vite,
    name: 'Vite',
    docs: 'https://vitejs.dev/guide/',
    customGlowColor: '#857BFF',
  },
  {
    Icon: Vitest,
    name: 'Vitest',
    docs: 'https://vitest.dev/guide/',
  },
  {
    Icon: JestSvgl,
    name: 'Jest',
    docs: 'https://jestjs.io/docs/getting-started',
  },
  {
    Icon: Vercel,
    name: 'Vercel',
    docs: 'https://vercel.com/docs',
    DarkIcon: DarkVercel,
  },
  {
    Icon: Turborepo,
    name: 'Turborepo',
    docs: 'https://turbo.build/repo/docs',
    DarkIcon: DarkTurborepo,
  },
  {
    Icon: Nx,
    name: 'Nx',
    docs: 'https://nx.dev/docs',
    DarkIcon: DarkNx,
  },
  {
    Icon: ESLintIcon,
    name: 'ESLint',
    docs: 'https://eslint.org/docs/latest/',
    DarkIcon: DarkESLintIcon,
  },
  {
    Icon: PrettierIcon,
    name: 'Prettier',
    docs: 'https://prettier.io/docs/',
    DarkIcon: DarkPrettierIcon,
  },

  // UI libraries & styling
  {
    Icon: shadcnui,
    name: 'shadcn/ui',
    docs: 'https://ui.shadcn.com/',
    customGlowColor: '#ffffff',
    DarkIcon: shadcnuiDark,
  },
  {
    Icon: MotionSvgl,
    name: 'Motion',
    docs: 'https://motion.dev/docs',
    customGlowColor: '#fff42b',
    DarkIcon: DarkMotionSvgl,
  },
  {
    Icon: MaterialUI,
    name: 'Material UI',
    docs: 'https://mui.com/material-ui/getting-started/',
    customGlowColor: '#007FFF',
  },
  {
    Icon: Mantine,
    name: 'Mantine',
    docs: 'https://mantine.dev/',
    customGlowColor: '#339AF0',
  },
  {
    Icon: BaseUI,
    name: 'Base UI',
    docs: 'https://base-ui.com/',
    DarkIcon: DarkBaseUI,
  },
  {
    Icon: AntDesign,
    name: 'Ant Design',
    docs: 'https://ant.design/docs/react/introduce',
    customGlowColor: '#1677FF',
  },
  {
    Icon: BetterAuth,
    name: 'Better Auth',
    docs: 'https://www.better-auth.com/docs',
    DarkIcon: DarkBetterAuth,
  },
  {
    Icon: RadixUI,
    name: 'Radix UI',
    docs: 'https://www.radix-ui.com/docs/primitives/overview/introduction',
    customGlowColor: '#AB6DFF',
    DarkIcon: RadixUIDark,
  },
  // {
  //   Icon: ,
  //   name: 'Zustand',
  //   docs: 'https://zustand-demo.pmnd.rs/',
  //   customGlowColor: '#553C2E',
  // },
  {
    Icon: StyledComponents,
    name: 'Styled Components',
    docs: 'https://styled-components.com/docs',
    customGlowColor: '#FAA0E6',
  },
  {
    Icon: Sass,
    name: 'Sass',
    docs: 'https://sass-lang.com/documentation',
  },
  {
    Icon: Expressjs,
    name: 'Express.js',
    docs: 'https://expressjs.com/',
    DarkIcon: DarkExpressjs,
  },

  // Especialización & nicho
  {
    Icon: Astro,
    name: 'Astro',
    docs: 'https://docs.astro.build/',
    customGlowColor: '#FF5D01',
    DarkIcon: AstroDark,
  },
  {
    Icon: SocketIOSvgl,
    name: 'Socket.IO',
    docs: 'https://socket.io/docs/',
    DarkIcon: DarkSocketIOSvgl,
  },
  {
    Icon: Neon,
    name: 'NeonDB',
    docs: 'https://neon.tech/docs',
    customGlowColor: '#00E599',
  },
  {
    Icon: Sentry,
    name: 'Sentry',
    docs: 'https://docs.sentry.io/',
    customGlowColor: '#794888',
  },
  {
    Icon: Deno,
    name: 'Deno',
    docs: 'https://deno.land/manual',
    customGlowColor: '#70FFAF',
    DarkIcon: DarkDeno,
  },
];
